version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "data"
      POSTGRES_USER: "stbuser"
      POSTGRES_PASSWORD: "stbuser"
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stbuser -d data"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
      container_name: worker
      build:
        dockerfile: Dockerfile
      depends_on:
        - rabbitmq

  bot:
    container_name: bot
    build:
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq